import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:iconsax/iconsax.dart';
import 'package:line_icons/line_icons.dart';
import 'color_constants.dart';
import 'font_constants.dart';

// const kIconBuilding = Icon(FontAwesomeIcons.building,color: kFontGreyColor,size: kIconSize,);
const kIconCalendar = Icon(CupertinoIcons.calendar, color: kFontGreyColor,size: kIconSize);
const  kIconBlackout = Icon(CupertinoIcons.calendar_badge_minus, color: kAppPinkColor,size: kIconSize);
// const  kIconStore = Icon(CupertinoIcons.building_2_fill, color: kFontGreyColor,size: kIconSize);
// const kIconMoney = Icon(FontAwesomeIcons.moneyBillTransfer, color: kNewGreenThemeColor,size: kIconSize);
// const kIconRoad = Icon (FontAwesomeIcons.road, color: kFontGreyColor,size: kIconSize,);
const kIconClockOpen =  Icon(Iconsax.clock,color: kGreenThemeColor,size: kIconSize);
const kIconClockClose =  Icon(Iconsax.clock,color: kAppPinkColor,size: kIconSize);
const kIconScissor =  Icon(Iconsax.scissor_1,color: kFontGreyColor,size: kIconSize,);
const kIconProducts =  Icon(LineIcons.gifts,color: kFontGreyColor,size: kIconSize,);
const kIconScissorWhite =  Icon(Iconsax.scissor_1,color: Colors.white,size: kIconSize,);
// const kIconShoppingItems =  Icon(FontAwesomeIcons.bagShopping,color: kFontGreyColor,size: kIconSize,);
const kIconStar =  Icon(Iconsax.star1, color: kBlueDarkColor,size: 25,);
const kIconStarWhite =  Icon(Iconsax.star1, color: Colors.white,size: kIconSize,);
const kIconCustomer =  Icon(Iconsax.personalcard, color:  kFontGreyColor,size: kIconSize,);
const kIconLocation =  Icon(Icons.location_on, color: kFontGreyColor,size: kIconSize,);
const kIconPen =  Icon(LineIcons.pen, color: kAppPinkColor,size: kIconSize,);
const kIconPhone =  Icon(LineIcons.phone, color: kFontGreyColor,size: kIconSize,);
const kIconLocationWhite =  Icon(Icons.location_on, color: Colors.white,size: kIconSize,);
const kIconApprovedGreen =  Icon(CupertinoIcons.checkmark_seal_fill, color: kNewGreenThemeColor,size: 15,);
// const kIconWavyMoneyGrey =  Icon(FontAwesomeIcons.moneyBillWave, color: kFaintGrey,size: 15,);
// const kIconWavyMoneyGreen =  Icon(FontAwesomeIcons.moneyBillWave, color: kNewGreenThemeColor,size: 13,);
const kIconFavouriteHeart =  Icon(Iconsax.heart, color:kGreenJavasThemeColor,size: 18 );
const kIconArrowLeft =  CircleAvatar(backgroundColor: kFontGreyColor, radius: 8, child: Icon(Icons.arrow_back, size: 12, color: kPureWhiteColor,));
const kIconArrowRight =  CircleAvatar(backgroundColor: kFontGreyColor, radius: 8, child: Icon(Icons.arrow_forward, size: 12, color: kPureWhiteColor,));
const kIconCancel =  Icon(Icons.cancel, color: kBlack,size: kIconSize,);
const kIconBackWhite =  Icon(Icons.cancel, color: kPureWhiteColor,size: 25,);
const kIconNotPaidIcon = Icon(Icons.flag_circle, color: Colors.red, size: 15,);
const kIconPaidIcon = Icon(Icons.check_circle_outline, color: kGreenThemeColor, size: 15,);
// main Icons
const kIconMessage = Icons.mark_email_read;
const kIconTransaction = Iconsax.bank;
const kIconAnalytics = Icons.auto_graph;
const kIconSuppliers = Icons.supervised_user_circle;
const kIconTeam = Icons.people;
const kIconStore= Icons.storefront;
const kIconPos= Icons.point_of_sale;
const kIconHome= Icons.home_max;

